name: 'my_project'
<<<<<<< HEAD
version: '1.0'
profile: 'my_project'
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'
=======
version: '1.0.0'
profile: 'my_profile'
target-path: 'target'
model-paths: ['models']
>>>>>>> 56506711db7a10b24b928c8e47b3def189b59fd3
